### ISSUE TITLE
Properly authenticate users with Auth0 instead of just using a query parameter

### ISSUE THREAD

**Issue by jkcarney** [jkcarney/wakatime-bot#4]
- [x] Figure out how tf Auth0 works
- [x] Figure out why it isnt working with wakatime api
- [x] ???
  - [x] Initialize user data with register command and send them link
  - [x] Have them authorize app and send initial token back
  - [x] Utilize initial token to get an access_token and refresh_token from `https://wakatime.com/oauth/token` 
  - [x] Ensure access_token works by making an API call and filling out rest of data in table 
  - [x] Store access_token and refresh_token in DB
  - Whenever getting user data from API:
    - [x] Utilize old refesh_token to get new access_token and new refresh_token
    - [x] Update existing DB entry with new access_token and new refresh_token
    - [x] Use new access_token to get user data
- [x] ??? 
- [x] profit

**Comment by Spyder-Monkey** [comment]
good comments
