### ISSUE TITLE
Migrate from sqlite to MySQL

### ISSUE THREAD

**Issue by jkcarney** [jkcarney/wakatime-bot#8]
- MySQL is faster and allows for more "production ready" SQL access
- It may also be much nicer because we could set up a MySQL server on our VPS (virtual private server) that runs Wakabot. Then if we wanted to test we could connect to the MySQL server remotely so we have a central location for all stored data
- It would hopefully be kinda easy because peewee supports and interfaces with many different types of SQL DBs out of the box

**Comment by samnoggle** [comment]
thats good!!! yeah passing the file back n forth is messy n this is def endgame for distribution in other servers. also SPEED
